
package JCHECKTIME;

import JCHECKTIME.EMPLEADOS.Empleados;
import static JCHECKTIME.JfrmIngresar.TEMPLATE_PROPERTY;
import JCHECKTIME.TOOLS.DigitalPersona.ConvertirStringTo;
import JCHECKTIME.TOOLS.METODOS.Fecha;
import com.digitalpersona.onetouch.DPFPDataPurpose;
import com.digitalpersona.onetouch.DPFPFeatureSet;
import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.DPFPSample;
import com.digitalpersona.onetouch.DPFPTemplate;
import com.digitalpersona.onetouch.capture.DPFPCapture;
import com.digitalpersona.onetouch.capture.event.DPFPDataAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPDataEvent;
import com.digitalpersona.onetouch.capture.event.DPFPErrorAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPErrorEvent;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusEvent;
import com.digitalpersona.onetouch.capture.event.DPFPSensorAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPSensorEvent;
import com.digitalpersona.onetouch.processing.DPFPEnrollment;
import com.digitalpersona.onetouch.processing.DPFPFeatureExtraction;
import com.digitalpersona.onetouch.processing.DPFPImageQualityException;
import com.digitalpersona.onetouch.processing.DPFPTemplateStatus;
import com.digitalpersona.onetouch.verification.DPFPVerification;
import com.digitalpersona.onetouch.verification.DPFPVerificationResult;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class JfrmRegistrarEntrada extends javax.swing.JFrame {

    //Varible que permite iniciar el dispositivo de lector de huella conectado
    // con sus distintos metodos.
    private DPFPCapture Lector = DPFPGlobal.getCaptureFactory().createCapture();
    //Varible que permite establecer las capturas de la huellas, para determina sus caracteristicas
    // y poder estimar la creacion de un template de la huella para luego poder guardarla
    private DPFPEnrollment Reclutador = DPFPGlobal.getEnrollmentFactory().createEnrollment();

    //Esta variable tambien captura una huella del lector y crea sus caracteristcas para auntetificarla
    // o verificarla con alguna guarda en la BD
    private DPFPVerification Verificador = DPFPGlobal.getVerificationFactory().createVerification();

    //Variable que para crear el template de la huella luego de que se hallan creado las caracteriticas
    // necesarias de la huella si no ha ocurrido ningun problema
    private DPFPTemplate template;
    public static String TEMPLATE_PROPERTY = "template";
    
    //Variables para la Huella digital
    private DPFPSample Sample = DPFPGlobal.getSampleFactory().createSample();
    private DPFPTemplate TemplateHuellaDig = DPFPGlobal.getTemplateFactory().createTemplate();
    
    public DPFPFeatureSet CaracteristicasSample;
    //public DPFPFeatureSet featuresverificacion;
    
    boolean HuellaValida=false;
    Empleados.strEmpleados[] ARR;
    
    public JfrmRegistrarEntrada() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Registrar entrada");
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Iconos/Huella.png")).getImage());
        
        this.addComponentListener(new ComponentAdapter() {
			@Override public void componentShown(ComponentEvent e) {
				init();
				start();
			}
			@Override public void componentHidden(ComponentEvent e) {
				stop();
			}
			
		});
        
        ListarEmpleados();
    }
    
    private void ListarEmpleados(){
        
        Empleados E=new Empleados();
        ARR=E.ListarEmpleados("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imgHuellaDig = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registre su huella para registrar la entrada");

        lblHora.setFont(new java.awt.Font("DS-Digital", 0, 36)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("HORA REGISTRADA");

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 0, 0));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Registre su huella");

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgHuellaDig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgHuellaDig, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:  _______________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        stop();
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    //region CAPTURAR HUELLA
    public void init()
	{
            Lector.addDataListener(new DPFPDataAdapter() {
            @Override public void dataAcquired(final DPFPDataEvent e) {
            SwingUtilities.invokeLater(new Runnable() {	public void run() {
            EnviarTexto("La Huella Digital ha sido Capturada");
            ProcesarCaptura(e.getSample());
            }});}
           });

           Lector.addReaderStatusListener(new DPFPReaderStatusAdapter() {
            @Override public void readerConnected(final DPFPReaderStatusEvent e) {
            SwingUtilities.invokeLater(new Runnable() {	public void run() {
            EnviarTexto("El lector de huella digital esta Activo.");
            }});}
            @Override public void readerDisconnected(final DPFPReaderStatusEvent e) {
            SwingUtilities.invokeLater(new Runnable() {	public void run() {
            EnviarTexto("El lectora de huella digital esta Desactivado o no Conectado.");
            }});}
           });

           Lector.addSensorListener(new DPFPSensorAdapter() {
            @Override public void fingerTouched(final DPFPSensorEvent e) {
            SwingUtilities.invokeLater(new Runnable() {	public void run() {
            EnviarTexto("El dedo ha sido colocado sobre el lector de huella.");
            }});}
            @Override public void fingerGone(final DPFPSensorEvent e) {
            SwingUtilities.invokeLater(new Runnable() {	public void run() {
            EnviarTexto("El dedo ha sido quitado del lector de Huella.");
            }});}
           });

           Lector.addErrorListener(new DPFPErrorAdapter(){
            public void errorReader(final DPFPErrorEvent e){
            SwingUtilities.invokeLater(new Runnable() {  public void run() {
            EnviarTexto("Error: "+e.getError());
            }});}
           });
	}

	protected void ProcesarCaptura(DPFPSample sample)
	{
            //Dibujar huella Capturada
            try
            {
                DibujarHuella(CrearImagenHuella(sample));
            }
            catch(Exception e)
            {
                //JOptionPane
                //(Frame, Mensaje, Titulo, Tipo)
                // Tipo(0) Error
                // Tipo(1) Informacion
                // Tipo(2) Advertencia
                // Tipo(3) Interragacion

                JOptionPane.showMessageDialog(null, e.toString(), "Exception" , 0);
            }
            
            
            for (int i = 0; i < ARR.length; i++)
            {
                DPFPSample HuellaBD;
                HuellaBD=ConvertirStringTo.Sample(ARR[i].Obj25_HuellaDig);
                
                CaracteristicasSample=extraerCaracteristicas(HuellaBD, DPFPDataPurpose.DATA_PURPOSE_ENROLLMENT);

                while(Reclutador.getTemplateStatus()== DPFPTemplateStatus.TEMPLATE_STATUS_INSUFFICIENT||
                      Reclutador.getTemplateStatus()== DPFPTemplateStatus.TEMPLATE_STATUS_UNKNOWN){
                    
                if (CaracteristicasSample != null)
                    try
                    {
                    System.out.println("Las caracteristicas de la huella han sido creadas");
                    Reclutador.addFeatures(CaracteristicasSample);// Agregar las caracteristicas de la huella a la plantilla a crear

                    }
                    catch (DPFPImageQualityException e) 
                    {
                    //JOptionPane
                        //(Frame, Mensaje, Titulo, Tipo)
                        // Tipo(0) Error
                        // Tipo(1) Informacion
                        // Tipo(2) Advertencia
                        // Tipo(3) Interragacion

                        JOptionPane.showMessageDialog(null, e.toString(), "DPFPImageQualityException" , 0);
                    }}

                System.out.println(Reclutador.getTemplateStatus());
                TemplateHuellaDig = Reclutador.getTemplate();
                
               
		// Process the sample and create a feature set for the enrollment purpose.
		DPFPFeatureSet features = extractFeatures(sample, DPFPDataPurpose.DATA_PURPOSE_VERIFICATION);

		// Check quality of the sample and start verification if it's good
                DPFPVerificationResult result = null;
		if (features != null)
		{
			// Compare the feature set with our template
			result = Verificador.verify(features, TemplateHuellaDig);
			ActualizarEstado(result.getFalseAcceptRate());
                        
			if (result.isVerified())
				EnviarTexto("La huella registrada coincide");
			else
				EnviarTexto("La huella registrada NO coincide");
		}
                try
                {
                    if(result.getFalseAcceptRate()!=0)
                {
                    lblResultado.setForeground(new java.awt.Color(255,0,0));
                    Aviso("Intente de nuevo");
                    HuellaValida=false;
                    stop();
                    
                    break;
                }
                    else
                    {
                        lblResultado.setForeground(new java.awt.Color(0,176,80));
                        Aviso("Identificacion verificada");
                        Fecha F=new Fecha();
                        lblHora.setText(F.getHora());
                        lblNombre.setText(ARR[i].Obj2_NombreEmpleado+" "+ARR[i].Obj3_Apellidos);
                        HuellaValida=true;
                    }
                }
                catch(Exception e)
                {
                    //JOptionPane
                    //(Frame, Mensaje, Titulo, Tipo)
                    // Tipo(0) Error
                    // Tipo(1) Informacion
                    // Tipo(2) Advertencia
                    // Tipo(3) Interragacion

                    JOptionPane.showMessageDialog(null, e.toString(), "Exception" , 0);
                }
            }
	}

	public void start()
	{
		Lector.startCapture();
		EnviarTexto("El lector de huellas se ha iniciado.");
	}

	public void stop()
	{
		Lector.stopCapture();
                EnviarTexto("El lector de huellas de ha detenido.");
	}

	public void Estado(String string) {
            
             try
            {
                 //lblEstado.setText(string);
            }
            catch(Exception e)
            {
            
            }
	}
	public void Aviso(String string) {
            
            try
            {
                 lblResultado.setText(string);
            }
            catch(Exception e)
            {
            
            }
		
	}
	public void EnviarTexto(String string) {
            try
            {
                 //lstModelo.addElement(string);
                System.out.println(string);
            }
            catch(Exception e)
            {
            
            }
	}
        
        public void DibujarHuella(Image image) {
            
            try
            {
                 imgHuellaDig.setIcon(new ImageIcon(
		 image.getScaledInstance(imgHuellaDig.getWidth(), imgHuellaDig.getHeight(), Image.SCALE_DEFAULT)));
            }
            catch(Exception e)
            {
            
            }
		
	}	
	public Image CrearImagenHuella(DPFPSample sample) {
            
            return DPFPGlobal.getSampleConversionFactory().createImage(sample);
            
	}
        
        protected DPFPFeatureSet  extraerCaracteristicas(DPFPSample sample, DPFPDataPurpose purpose)
	{
		DPFPFeatureExtraction extractor = DPFPGlobal.getFeatureExtractionFactory().createFeatureExtraction();
		try {
			return extractor.createFeatureSet(sample, purpose);
		} catch (DPFPImageQualityException e) {
			return null;
		}
	}
        
	protected DPFPFeatureSet extractFeatures(DPFPSample sample, DPFPDataPurpose purpose)
	{
		DPFPFeatureExtraction extractor = DPFPGlobal.getFeatureExtractionFactory().createFeatureExtraction();
		try {
			return extractor.createFeatureSet(sample, purpose);
		} catch (DPFPImageQualityException e) {
			return null;
		}
	}
        
        private void ActualizarEstado(int FAR)
	{
		// Show "False accept rate" value
		Estado(String.format("ERROR = %1$s", FAR));
                System.out.println(String.format("ERROR = %1$s", FAR));
	}
        
        public DPFPTemplate getTemplate() {
            return template;
        }

        public void setTemplate(DPFPTemplate template) {
            DPFPTemplate old = this.template;
            this.template = template;
            firePropertyChange(TEMPLATE_PROPERTY, old, template);
        }
      //endregion CAPTURAR HUELLA 
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmRegistrarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmRegistrarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmRegistrarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmRegistrarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmRegistrarEntrada().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel imgHuellaDig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
